Searchanise = window.Searchanise || {};
Searchanise.templates = {
Platform:'magento',
WidgetsEnabled:'Y',
SearchInput:'#snize-input',
UseGATrackParam:'N',
AutocompleteShow:true,
AutocompleteStyle:'ITEMS_MODERN',
AutocompleteSuggestionCount:0,
AutocompleteCategoriesCount:5,
AutocompletePagesCount:0,
AutocompleteItemCount:7,
AutocompleteHighlight:true,
AutocompleteShowViewAllLink:true,
AutocompleteShowBrand:false,
AutocompleteShowBuyNotice:false,
AutocompleteShowPrice:true,
AutocompleteShowListPrice:false,
AutocompleteShowProductImages:true,
AutocompleteShowProductCode:true,
AutocompleteShowRecent:true,
AutocompleteShowMobileWidget:true,
AutocompleteShowOnlyInStock:false,
AutocompleteShowEmptyFieldHTML:false,
AutocompleteEmptyFieldHTML:'',
AutocompleteShowResultsHTML:false,
AutocompleteResultsHTML:'',
AutocompleteShowNoResultsHTML:false,
AutocompleteNoResultsHTML:'',
AutocompleteShowInStockStatus:false,
AutocompleteResultsOrder:["categories","suggestions","products","pages"],
AutocompleteZeroPriceAction:'show_zero_price',
LabelAutocompleteSuggestions:'Popular suggestions',
LabelAutocompleteCategories:'Categories',
LabelAutocompletePages:'Pages',
LabelAutocompleteProducts:'Products',
LabelAutocompleteMoreProducts:'View all [count] items',
LabelAutocompleteNothingFound:'Sorry, nothing found for [search_string].',
LabelAutocompleteSearchInputPlaceholder:'',
LabelAutocompleteMobileSearchInputPlaceholder:'Search our store...',
LabelAutocompleteInStock:'In Stock',
LabelAutocompleteOutOfStock:'Out Of Stock',
LabelAutocompleteSku:'SKU',
LabelAutocompleteResultsFound:'Showing [count] results for "[search_string]"',
LabelAutocompleteDidYouMean:'Did you mean: [suggestions]?',
LabelAutocompleteNoSearchQuery:'Type something above to start search...',
LabelAutocompleteNumReviews:'[count] review(s)',
LabelAutocompleteZeroPriceText:'Contact us for price',
AppSupportCoin:'N',
ReviewsShowRating:'N',
PriceFormatSymbol:'$',
PriceFormatBefore:'$',
PriceFormatAfter:'',
PriceFormatDecimals:2,
PriceFormatRate:1,
PriceFormatDecimalSeparator:'.',
PriceFormatThousandsSeparator:',',
ResultsShow: false
};