
var baseHtml="";
baseHtml += "<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD HTML 4.01\/\/EN\"";
baseHtml += "\"http:\/\/www.w3.org\/TR\/html4\/strict.dtd\">";
baseHtml += "<html>";
baseHtml += "  <head>";
baseHtml += "    <title>E.K.Holbrook<\/title>";
baseHtml += "	<meta http-equiv=\"pragma\" content=\"no-cache\" \/>";
baseHtml += "	<meta http-equiv=\"cache-control\" content=\"no-cache\"\/>";
baseHtml += "	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\" \/>";
baseHtml += "	<meta name=\"viewport\" content=\"width=device-width\" \/>";
baseHtml += "<meta http-equiv=\"Content-Type\" content=\"text\/html; charset=UTF-8\" \/>";
baseHtml += "	 <script src=\"https:\/\/ajax.googleapis.com\/ajax\/libs\/jquery\/2.1.3\/jquery.min.js\"><\/script>";
baseHtml += "	<script src=\"https:\/\/ajax.googleapis.com\/ajax\/libs\/jqueryui\/1.11.3\/jquery-ui.min.js\"><\/script>";
baseHtml += "	<script src=\"https:\/\/dl.dropboxusercontent.com\/u\/508866\/webcode\/lamedomain\/pagegen.js\"><\/script>";
baseHtml += "	<script type=\"text/javascript\" src=\"https:\/\/dl.dropboxusercontent.com\/u\/508866\/webcode\/lamedomain\/js\/FeedEk.js\"><\/script>";
baseHtml += "	<link rel=\"stylesheet\" type=\"text\/css\" href=\"https:\/\/dl.dropboxusercontent.com\/u\/508866\/webcode\/lamedomain\/sandboxlight.css\">";
baseHtml += "<\/head>";
baseHtml += "<body>";
baseHtml += "	<span class=\"cssstyle\"> <\/span>";
baseHtml += "  	<div id=\"container\">";
baseHtml += "		<div id=\"siteTitle\"><\/div>";
baseHtml += "		<div id=\"menutrigger\"><\/div>";
baseHtml += "		<div id=\"header\">";
baseHtml += "			<ul id=\"menu\">";
baseHtml += "				<div id=\"themenu\"><\/div>";
baseHtml += "			<\/ul>";
baseHtml += "		<\/div>";
baseHtml += "			<div id=\"title\">";
baseHtml += "				<h1><\/h1>";
baseHtml += "			<\/div>";
baseHtml += "		<div id=\"main\">";
baseHtml += "			<div id=\"contentmain\">";
baseHtml += "				<div id=\"logo\"><\/div>";
baseHtml += "				<div id=\"content\"><\/div>";
baseHtml += "			<\/div>";
baseHtml += "			<div class=\"top\"><a href=\"#top\">Back To Top<\/a><\/div>";
baseHtml += "		<\/div>";
baseHtml += "		<ul id=\"footermenu\">";
baseHtml += "			<div id=\"thefootermenu\"><\/div>";
baseHtml += "		<br style=\"clear:both;\"\/>";
baseHtml += "		<\/ul>";
baseHtml += "		<div id=\"footer\"><\/div>";
baseHtml += "	<\/div>";
baseHtml += "  <\/body>";
baseHtml += "<\/html>";


document.write(baseHtml);