window.title=["Why It Works","Deals Near You","Gift Card Deals","Merchandise Deals","Travel Deals"];
window.csswidth="680";

//window.csswidth=prompt("Width of content (1000 - 650px works well)");

window.$slidecontent1  ="<div class=\"slideheader\"><div class=\"slidetitle\" title=\"Drag a Slide to Re-Order Them!\">TITLE</div><div class=\"greybar\"></div></div><div class=\"slidebody\"><div class=\"top\"></div><div class=\"intro\">";

window.$slidecontent1 +="<h2>Your points are the perfect travel buddy.</h2><p>They're always up for going someplace new to help you save on over 160 brands and more than 20,000 properties. Customers have saved, on average, 17% with Citi Easy Deals.</p><br style=\"clear:both;\"/></div>";

window.$slidecontent1 +="<div class=\"expand closed\" > <div class=\"expand_content\"><p>Here are a few examples:</p><div class=\"hotels\"><div><img src=\"https://dl.dropboxusercontent.com/u/508866/citi/images/travelhotel2.jpg\"/></div><div><img src=\"https://dl.dropboxusercontent.com/u/508866/citi/images/travelhotel1.jpg\"/></div><div><img src=\"https://dl.dropboxusercontent.com/u/508866/citi/images/travelhotel3.jpg\"/></div><div><img src=\"https://dl.dropboxusercontent.com/u/508866/citi/images/travelhotel4.jpg\"/></div><div><img src=\"https://dl.dropboxusercontent.com/u/508866/citi/images/travelhotel5.jpg\"/></div><div><img src=\"https://dl.dropboxusercontent.com/u/508866/citi/images/travelhotel6.jpg\"/></div></div><div class=\"savetoday\"></div></div><div class=\"easytip\"><span class=\"easy_title\">EASY TIP <b>NO. 4</b></span><div class=\"easy_content\"> <h2>Even when you're<br/>traveling, deals are<br/>always close by.</h2><p>Visit <b>citieasydeals.com/start</b><br/>on your mobile device, and<br/> you can search for deals in<br/>your destination city. Then<br/> use your points to save on<br/>local dining, shopping and<br/>entertainment.<br/><br/></p><br style=\"clear:both;\"/></div> <br style=\"clear:both;\"/> </div></div><div class=\"toggle easytip_closed min\"><span class=\"easy_title\">EASY TIP <b>NO. 4</b></span><div class=\"easy_plus pulseate\">+</div> 	<div class=\"ex ex_hide\">x</div></div><div class=\"toggle clickme show\">Expand to learn more <div class=\"plus pulseblue\">+</div></div><div class=\"toggle hideme hide\">CLOSE X</div><br style=\"clearit\"/></div>";


//////////
window.$slidecontent2  ="<div class=\"slidebody\"><div class=\"top\"></div>";
// intro paragraph
window.$slidecontent2 +="<div class=\"intro\"><h2>That is Near You!</h2><p>Now eldest new tastes plenty mother called misery get. Longer excuse for county nor except met its things. Now eldest new tastes plenty mother called misery get. Longer excuse for county nor except met its things.<br/><br/> Now eldest new tastes plenty mother called misery get. Longer excuse for county nor except met its things. Now eldest new tastes plenty mother called misery get. Longer excuse for county nor except met its things. </p><br style=\"clear:both;\"/></div>";

//expand content
window.$slidecontent2 +="<div class=\"expand closed\" ><div class=\"expand_content\"><p>Here are a few examples:</p><p> Narrow enough  are. Hold who what come that seen read age its. Contained or estimable earnestly so perceived. Imprudence he in sufficient cultivated. Delighted promotion improving acuteness an newspaper offending he. Misery in am secure theirs giving an. Design on longer thrown oppose am.</p><p> Narrow enough  are. Hold who what come that seen read age its. Contained or estimable earnestly so perceived. Imprudence he in sufficient cultivated. Delighted promotion improving acuteness an newspaper offending he. Misery in am secure theirs giving an. Design on longer thrown oppose am.</p><p> Narrow enough  are. Hold who what come that seen read age its. Contained or estimable earnestly so perceived. Imprudence he in sufficient cultivated. Delighted promotion improving acuteness an newspaper offending he. Misery in am secure theirs giving an. Design on longer thrown oppose am.</p><p> Narrow enough  are. Hold who what come that seen read age its. Contained or estimable earnestly so perceived. Imprudence he in sufficient cultivated. Delighted promotion improving acuteness an newspaper offending he. Misery in am secure theirs giving an. Design on longer thrown oppose am.</p>";

window.$slidecontent2 +="<div class=\"savetoday\"></div></div><div class=\"easytip\"><span class=\"easy_title\">EASY TIP <b>NO. 4</b></span><div class=\"easy_content\">";
// easy tip title
window.$slidecontent2 +="<h2>Forget Your Worries And Travel Today! - We're always close by.</h2>";
// easy tip content
window.$slidecontent2 +="<p>Visit <b>citieasydeals.com/start</b><br/>on your mobile device, and<br/> you can search for deals in<br/>your destination city. Then<br/> use your points to save on local dining, shopping and<br/>entertainment.<br/><br/></p><br style=\"clear:both;\"/></div> <br style=\"clear:both;\"/> </div></div><div class=\"toggle easytip_closed min\"><span class=\"easy_title\">EASY TIP <b>NO. 4</b></span><div class=\"easy_plus pulseate\">+</div> 	<div class=\"ex ex_hide\">x</div></div><div class=\"toggle clickme show\">Expand to learn more <div class=\"plus pulseblue\">+</div></div><div class=\"toggle hideme hide\">CLOSE X</div><br style=\"clearit\"/></div>";
////////

window.$footer ="<div class=\"footl\"> <a href=\" \"  class=\"faq\">FAQ</a> <a href=\" \"  class=\"contact\">CONTACT US</a> </div> <div class=\"footlogo\"></div>  <div class=\"footf\"> The information contained within is accurate as of 2/04/2014 and is subject to change. For a current listing of offers and complete terms and conditions regarding the Citi Easy Deals program, visit citieasydeals.com.<br/><br/> Deals Near You supplier participation varies, may be determined by location and is at the sole discretion of the supplier. Participating merchants and offers may change and are not guaranteed.<br/><br/> This website is owned and operated by Destination Rewards, Inc., a business unit of Deluxe Financial Services, Inc., the provider of Citi Easy Deals. Portions of the website are covered by patents, including without limitation U.S. Patent Number 7,925,533, and/or pending patent applications.<br/><br/> Destination Rewards <a  class=\"termsBox privacy\">Privacy Policy</a><br/> Citi Easy Deals <a  class=\"termsBox terms\">Terms and Conditions</a><br/><br/>&copy; Copyright 2014 Destination Rewards, Inc. All Rights Reserved.<br/> </div>";


